---
title: "Practical Machine Learning - Writeup"
author: "Roberto Bruno Martins"
date: "20-12-2014"
output: html_document
---

This is an introduction, explaining the assignment, course, github repo URL, credits, etc.

## Background Information

This section is a copy of the exercise text, provided for reference.

### Background

Using devices such as *Jawbone Up*, *Nike FuelBand*, and *Fitbit* it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the [PUC-RIO Human Activity Report](http://groupware.les.inf.puc-rio.br/har) website (see the section on the Weight Lifting Exercise Dataset). 

### Data

The training data for this project are available [here](https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv).

The test data are available [here](https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv).

The data for this project come from [this source](http://groupware.les.inf.puc-rio.br/har). If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment. 

### What should be submitted

The goal of your project is to predict the manner in which they did the exercise. This is the `classe` variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases. 

## Reproducibility

In order to make the code as reproducible as possible, the following definitions were followed:

* All data files will reside in a "./data" subdirectory. This includes the training and test data provided;
* All operations using random numbers will be preceded by a `set.seed(12345)` command;
* The following packages and versions were used during this analysis:
    + 
## Loading and Preparing the data

## Training and Cross-Validating the Model

## Model Analysis

## Predictions

The following code is designed to generate the file for the required 20 predictions for the programming assignment related to this model. 